### ISSUE TITLE
Ludwich asked

### ISSUE THREAD

**Issue by ludwich66** [mdlougheed/DP32G030-Reference-Manual#1]
What added value does your repo have compared to Adam's existing repo?
https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/hardware/DP32G030
Grüße Ludwich

**Comment by mdlougheed** [comment]
My thought was to contribute an English language translation if the
DP32G030 reference manual to the wiki.

If you want, pull a copy over.

Cheers
MDL

**Comment by ludwich66** [comment]
I added you translation to the main wiki tree
https://github.com/ludwich66/Quansheng_UV-K5_Wiki/tree/main/hardware
THNX Ludwich

**Comment by mdlougheed** [comment]
Great!
Thank you.
MDL
